version: '3.8'

services:
  web:
    build: .
    container_name: bookmarks_backend
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn mysite.wsgi:application --reload --timeout 1000 --bind 0.0.0.0:8000"
    # command: gunicorn inventory_project.wsgi:application --reload --timeout 1000 --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - .:/usr/src/app/
    expose:
      - 8000
    env_file:
      - ./.docker_env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    container_name: bookmarks_backend_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=nick
      - POSTGRES_PASSWORD=33992433
      - POSTGRES_DB=bookmarks_db
  
  nginx:
    build: ./nginx
    container_name: bookmarks_nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      # - ./certbot/www:/var/www/certbot/:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - web
  
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw

volumes:
  postgres_data:
  static_volume:
  media_volume:
